### PR TITLE
Internal API unit-testing

### PR DESCRIPTION
**Pull request by ghost**
PRs can't merge without passing Travis tests, so we need this before anything else (We are not passing since 6607913b66).

### CODE REVIEW

**Comment by ghost** [comment]
Not everything is done yet.

**Comment by ghost** [comment]
There's one thing I wonder. Since hooks are calling the API or the real function, is it really necessary to verify every hook? (Especially since we can't really test all the stat flavors on the same architecture).

**Comment by nil0x42** [comment]
we must be able to detect any potential regression, event is we do some big internal api modifications.
this way we'll be able to at least assert that all hooks and internal api functions are at least callable.

therefore, keep in mind that thos unit tests do not intend to test EVERYTING, we just need to be sure that all calls are currently working.

do not try to get a 100% code coverage for now, just do stupid calls,
and we will be able to improve them if needed later, thanks to coveralls which will keep a track of covered lines.

**Comment by ghost** [comment]
@nil0x42 : It's not about coverage. It's just that when compiling, we only get one of the 4 flavors of stat/lstat, and only one of the two readdir/fopen.

I'll only test the internal API. But I need you on the drop_shell_backdoor() test.

**Pull request merged**
