### PR TITLE
Coveralls integration

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nil0x42** [comment]
i will add a commit to fix `make coverage`, and then check if the pull request passes the tests

**Comment by nil0x42** [comment]
for the visibility tests, i cherry picked your commit 270279c2ce920411b30b2daf776dff0ecb80b248,
and added a few commits in order to completely refactor the way we build the rootkit with correct visibility.

please take a look pull request #50

**Comment by ghost** [comment]
`make coverage` is only ever used by Travis, no need to worry about that part.

**Comment by ghost** [comment]
I'm merging without the commit inducing a failed build, since it's used elsewhere.

**Pull request merged**
