### PR TITLE
 fix(core): force init() constructor call 

### PR DESCRIPTION
**Pull request by chqrly**
show the Developer's Guide

### CODE REVIEW

**Comment by ghost** [comment]
It seems REALLY hack-ish, I won't merge immediately. And I will amend 70ef8f2

**Comment by nil0x42** [comment]
i ll accept this pull request.
therefore, there is a test that should be done later (and i created an issue for it):
    https://github.com/unix-thrust/beurk/issues/58

**Comment by nil0x42** [comment]
ah, didn't saw that @mzap is not ok to merge.

@mzap : what do you find hacky ?

**Comment by nil0x42** [comment]
(except for the commit message, which indeed deserves an amend :dancers:)

**Comment by ghost** [comment]
Calling init() on every hooked function seemed hack-ish. But I did some digging and there's no other way to deal with that since SElinux does explicitely forbid some LD_PRELOAD shenanigans on occasion. (But it looks like it's only fopen[64] that we have a problem with, apparently because SElinux calls that function beforehand, can someone check that ?)

**Pull request closed without merging**
