### PR TITLE
Finish Internal api quicktests

### PR DESCRIPTION
**Pull request by nil0x42**
the `tests/core/internal-api` test suite has been refactored and completed,
in order to test all internal api functions correctly.

just a little hack: cleanup_login_records() is not tested, because testing it cannot really be done outside of functional tests.

### CODE REVIEW

**Comment by ghost** [comment]
And there I was, banging my head on the desk wondering how to tackle cleanup_login_records(). I will add a commit removing open() checks. @chqrly will be able to merge after that.

**Comment by nil0x42** [comment]
okay, i tried chroot, but openpty also requires /dev/pts to succeed,
if anything fails our own utmp/wtmp files can be impacted,
this is a pain for the ass,

only reliably testable through functional tests

**Comment by ghost** [comment]
Everything is looking good. Merging.

**Comment by nil0x42** [comment]
okay

**Pull request merged**
