### PR TITLE
Jagu/functionnal

### PR DESCRIPTION
**Pull request by jagu-sayan**
Please, check if is good for you :tropical_drink:

### CODE REVIEW

**Comment by jagu-sayan** [comment]
More test to come tomorrow.

**Comment by jagu-sayan** [comment]
> BEURK_INSTALL_DIR is defined in our beurk.conf, you can't set it in the Makefile.
> On another note, "CAREFUL, this command infects[...]" would be more appropriate.
> - mzap
1. I set BEURK_INSTALL_DIR only in debug mode.
   This can be an appropriate behavior that this option only work in "production mode".
   It's the only way I have found to make unit test on `make infect` and `make disinfect`.
   Maybe we need to clarify this behavior in beurk.conf file.
2. CAREFUL --> done

**Comment by nil0x42** [comment]
maybe we can consider changing the variable name from BEURK_INSTALL_DIR into BEURK_INFECT_DIR, it looks more appropriate

**Comment by jagu-sayan** [comment]
@mzap @chqrly @nil0x42 I rename BEURK_INSTALL_DIR to BEURK_INFECT_DIR.
I also add a comment in beurk.conf file:  

``` diff
-# str: where to store infected
-INSTALL_DIR = /lib
+# str: where to store infected, only work in `production` mode
+INFECT_DIR = /lib
```

**Comment by ghost** [comment]
Looks fine, merging now.

**Pull request merged**
